api: v1

run:
- gomplate: |-
    # ----------------
    # STACK {{ .name }}
    # STAGE {{ index .status .id }}
    {{ . | toYAML }}
  output:
  - stderr

postRun:
- gomplate: |-
    # ----------------
    # STACK {{ .name }}
    {{ . | toYAML }}
  output:
  - stderr

stacks:
- example-01

libs:
- git: git@github.com:kruglovmax/stack-examples.git
  ref: master
