api: v1

run:
- gitclone: git@gitlab.allabout.me:infra/pipeline-templates.git
  dir: .tmp
- jsonnet:
  - .tmp/golang.jsonnet
  output:
  - yml2var: locals.golang_pipeline
- gomplate: |-
    {{ .locals.golang_pipeline | toYAML }}
  output:
  - stderr
