api: v1

run:
- gomplate: |-
    {{- defineDatasource "s3example" ( printf "s3://infra-click-terraform-state/eks-ops-us-east-1-infra-click" ) }}
    {{- $test := ds "s3example" -}}
    {{ index ($test.outputs.cluster_arn.value | strings.Split ":") 4 }}
  output:
  - stderr
